/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wowotek.dk.gui;

import com.wowotek.dk.ErrorReporting;
import com.wowotek.dk.Util;
import com.wowotek.dk.auth.Hash;
import com.wowotek.dk.auth.Session;
import com.wowotek.dk.auth.authclasses.UserCredentials;
import com.wowotek.dk.auth.authclasses.UserData;
import com.wowotek.dk.db.DBAuthUserCredentials;
import com.wowotek.dk.db.DBAuthUserData;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class FormLogin extends javax.swing.JFrame
{

    private final ErrorReporting er;
    private final DBAuthUserCredentials dbuc;
    private final DBAuthUserData dbud;
    
    private final Session s;
    
    public UserCredentials InputUC;
    public UserData InputUD;
    
    public UserData CreateAccountUD;
    public UserCredentials CreateAccountUC;
    
    public boolean SessionCond = false;
    public boolean Inputed = false;
    
    public FormLogin(ErrorReporting er, DBAuthUserCredentials dbuc, DBAuthUserData dbud)
    {
        this.er = er;
        this.dbuc = dbuc;
        this.dbud = dbud;
        this.s = new Session(dbuc, dbud, er);
        initComponents();
        moreInit();
    }

    private void moreInit()
    {
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        RegisterFormData = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        label_name5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        label_name6 = new javax.swing.JLabel();
        NamaLengkapField = new javax.swing.JTextField();
        label_name7 = new javax.swing.JLabel();
        LegalIDField = new javax.swing.JTextField();
        TTLField = new javax.swing.JTextField();
        label_name8 = new javax.swing.JLabel();
        Phone1Field = new javax.swing.JTextField();
        label_name9 = new javax.swing.JLabel();
        label_name10 = new javax.swing.JLabel();
        Phone2Field = new javax.swing.JTextField();
        label_name11 = new javax.swing.JLabel();
        WorkField = new javax.swing.JTextField();
        label_name12 = new javax.swing.JLabel();
        WorkPlaceField = new javax.swing.JTextField();
        RF_btnNext = new javax.swing.JButton();
        RF_btnCancel = new javax.swing.JButton();
        RegisterFormCredentials = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        label_name13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        label_name14 = new javax.swing.JLabel();
        CAUsernameField = new javax.swing.JTextField();
        label_name15 = new javax.swing.JLabel();
        CAEmailField = new javax.swing.JTextField();
        label_name16 = new javax.swing.JLabel();
        label_name17 = new javax.swing.JLabel();
        RF_btnCreateAccount = new javax.swing.JButton();
        RF_btnPrevious = new javax.swing.JButton();
        CAPasswordField = new javax.swing.JPasswordField();
        CAConfirmPasswordField = new javax.swing.JPasswordField();
        WaitFrameDialog = new javax.swing.JDialog();
        jPanel13 = new javax.swing.JPanel();
        label_name19 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        label_name3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        label_name2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        label_name = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        label_name1 = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        checkbox1 = new java.awt.Checkbox();
        LoginButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        label_name18 = new javax.swing.JLabel();
        NewAccountButton = new javax.swing.JButton();
        label_name4 = new javax.swing.JLabel();
        ForgetPasswordButton = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(1, 50, 67));

        label_name5.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        label_name5.setForeground(new java.awt.Color(255, 255, 255));
        label_name5.setText("REGISTER FORM");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wowotek/dk/gui/image/FixLogoKecil.png"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        label_name6.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        label_name6.setForeground(new java.awt.Color(255, 255, 255));
        label_name6.setText("Nama Lengkap *");

        label_name7.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        label_name7.setForeground(new java.awt.Color(255, 255, 255));
        label_name7.setText("ID KTP/Passport/SIM *");

        label_name8.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        label_name8.setForeground(new java.awt.Color(255, 255, 255));
        label_name8.setText("Tempat, Tgl Lahir *");

        label_name9.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        label_name9.setForeground(new java.awt.Color(255, 255, 255));
        label_name9.setText("No. Telp 1 *");

        label_name10.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        label_name10.setForeground(new java.awt.Color(255, 255, 255));
        label_name10.setText("No. Telp 2");

        label_name11.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        label_name11.setForeground(new java.awt.Color(255, 255, 255));
        label_name11.setText("Pekerjaan *");

        label_name12.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        label_name12.setForeground(new java.awt.Color(255, 255, 255));
        label_name12.setText("Tempat Kerja *");

        RF_btnNext.setBackground(new java.awt.Color(101, 198, 187));
        RF_btnNext.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        RF_btnNext.setForeground(new java.awt.Color(1, 50, 67));
        RF_btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wowotek/dk/gui/image/Create.png"))); // NOI18N
        RF_btnNext.setText("Next");
        RF_btnNext.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                RF_btnNextActionPerformed(evt);
            }
        });

        RF_btnCancel.setBackground(new java.awt.Color(101, 198, 187));
        RF_btnCancel.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        RF_btnCancel.setForeground(new java.awt.Color(1, 50, 67));
        RF_btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wowotek/dk/gui/image/Logout.png"))); // NOI18N
        RF_btnCancel.setText("Cancel");
        RF_btnCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                RF_btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_name8)
                            .addComponent(label_name9)
                            .addComponent(label_name10)
                            .addComponent(label_name11)
                            .addComponent(label_name12))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(WorkPlaceField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(WorkField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Phone2Field)
                                    .addComponent(Phone1Field)
                                    .addComponent(TTLField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label_name7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_name6, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LegalIDField)
                            .addComponent(NamaLengkapField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(RF_btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(RF_btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_name5)
                .addGap(42, 42, 42))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label_name5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_name6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NamaLengkapField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_name7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LegalIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_name8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TTLField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_name9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Phone1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_name10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Phone2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_name11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WorkField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_name12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WorkPlaceField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RF_btnCancel)
                    .addComponent(RF_btnNext))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout RegisterFormDataLayout = new javax.swing.GroupLayout(RegisterFormData.getContentPane());
        RegisterFormData.getContentPane().setLayout(RegisterFormDataLayout);
        RegisterFormDataLayout.setHorizontalGroup(
            RegisterFormDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        RegisterFormDataLayout.setVerticalGroup(
            RegisterFormDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel5.setBackground(new java.awt.Color(1, 50, 67));

        label_name13.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        label_name13.setForeground(new java.awt.Color(255, 255, 255));
        label_name13.setText("CREATE ACCOUNT");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wowotek/dk/gui/image/FixLogoKecil.png"))); // NOI18N

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        label_name14.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        label_name14.setForeground(new java.awt.Color(255, 255, 255));
        label_name14.setText("Username *");

        CAUsernameField.setForeground(new java.awt.Color(1, 1, 1));

        label_name15.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        label_name15.setForeground(new java.awt.Color(255, 255, 255));
        label_name15.setText("E-mail *");

        CAEmailField.setForeground(new java.awt.Color(1, 1, 1));

        label_name16.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        label_name16.setForeground(new java.awt.Color(255, 255, 255));
        label_name16.setText("Password *");

        label_name17.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        label_name17.setForeground(new java.awt.Color(255, 255, 255));
        label_name17.setText("Confirm Password *");

        RF_btnCreateAccount.setBackground(new java.awt.Color(101, 198, 187));
        RF_btnCreateAccount.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        RF_btnCreateAccount.setForeground(new java.awt.Color(1, 50, 67));
        RF_btnCreateAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wowotek/dk/gui/image/Create.png"))); // NOI18N
        RF_btnCreateAccount.setText("Create account");
        RF_btnCreateAccount.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                RF_btnCreateAccountActionPerformed(evt);
            }
        });

        RF_btnPrevious.setBackground(new java.awt.Color(101, 198, 187));
        RF_btnPrevious.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        RF_btnPrevious.setForeground(new java.awt.Color(1, 50, 67));
        RF_btnPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wowotek/dk/gui/image/Logout.png"))); // NOI18N
        RF_btnPrevious.setText("Previous");
        RF_btnPrevious.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                RF_btnPreviousActionPerformed(evt);
            }
        });

        CAPasswordField.setForeground(new java.awt.Color(1, 1, 1));

        CAConfirmPasswordField.setForeground(new java.awt.Color(1, 1, 1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_name13)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_name15)
                                    .addComponent(label_name16)
                                    .addComponent(label_name17)
                                    .addComponent(label_name14, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(CAConfirmPasswordField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CAPasswordField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CAEmailField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CAUsernameField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(RF_btnCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RF_btnPrevious, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(27, 27, 27))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(label_name13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_name14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CAUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_name15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CAEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_name16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CAPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CAConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_name17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RF_btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RF_btnCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout RegisterFormCredentialsLayout = new javax.swing.GroupLayout(RegisterFormCredentials.getContentPane());
        RegisterFormCredentials.getContentPane().setLayout(RegisterFormCredentialsLayout);
        RegisterFormCredentialsLayout.setHorizontalGroup(
            RegisterFormCredentialsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        RegisterFormCredentialsLayout.setVerticalGroup(
            RegisterFormCredentialsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        WaitFrameDialog.setTitle("Please Wait...");

        jPanel13.setBackground(new java.awt.Color(1, 50, 67));

        label_name19.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        label_name19.setForeground(new java.awt.Color(255, 255, 255));
        label_name19.setText("Mohon Menunggu, Sedang Membuat Akun");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_name19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_name19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout WaitFrameDialogLayout = new javax.swing.GroupLayout(WaitFrameDialog.getContentPane());
        WaitFrameDialog.getContentPane().setLayout(WaitFrameDialogLayout);
        WaitFrameDialogLayout.setHorizontalGroup(
            WaitFrameDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        WaitFrameDialogLayout.setVerticalGroup(
            WaitFrameDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SuperBooks - Login");

        jPanel8.setBackground(new java.awt.Color(1, 50, 67));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wowotek/dk/gui/image/FixLogoBesar.png"))); // NOI18N

        label_name3.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        label_name3.setForeground(new java.awt.Color(255, 255, 255));
        label_name3.setText("WELCOME");

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(27, 188, 155));

        label_name2.setFont(new java.awt.Font("Helvetica", 0, 19)); // NOI18N
        label_name2.setForeground(new java.awt.Color(255, 255, 255));
        label_name2.setText("LOGIN FORM");

        jPanel1.setBackground(new java.awt.Color(27, 188, 155));
        jPanel1.setBorder(null);

        label_name.setFont(new java.awt.Font("Helvetica", 0, 19)); // NOI18N
        label_name.setForeground(new java.awt.Color(255, 255, 255));
        label_name.setText("Password");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PasswordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_name, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_name, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(27, 188, 155));
        jPanel3.setBorder(null);

        label_name1.setFont(new java.awt.Font("Helvetica", 0, 19)); // NOI18N
        label_name1.setForeground(new java.awt.Color(255, 255, 255));
        label_name1.setText("Username");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel10.setBackground(new java.awt.Color(27, 188, 155));

        jPanel12.setBackground(new java.awt.Color(27, 188, 155));

        checkbox1.setEnabled(false);
        checkbox1.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        checkbox1.setForeground(new java.awt.Color(255, 255, 255));
        checkbox1.setLabel("   Remember my password");

        LoginButton.setBackground(new java.awt.Color(1, 50, 67));
        LoginButton.setFont(new java.awt.Font("Helvetica", 0, 15)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wowotek/dk/gui/image/Login.png"))); // NOI18N
        LoginButton.setText("  Login");
        LoginButton.setActionCommand("Simpan");
        LoginButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                LoginButtonActionPerformed(evt);
            }
        });

        CancelButton.setBackground(new java.awt.Color(1, 50, 67));
        CancelButton.setFont(new java.awt.Font("Helvetica", 0, 15)); // NOI18N
        CancelButton.setForeground(java.awt.Color.white);
        CancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wowotek/dk/gui/image/Logout.png"))); // NOI18N
        CancelButton.setText("  Cancel");
        CancelButton.setActionCommand("Simpan");
        CancelButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(checkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginButton)
                    .addComponent(CancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LoginButton.getAccessibleContext().setAccessibleName("LoginButton");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(label_name2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_name2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel11.setBackground(new java.awt.Color(1, 50, 67));

        label_name18.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        label_name18.setForeground(new java.awt.Color(255, 255, 255));
        label_name18.setText("Create account");

        NewAccountButton.setBackground(new java.awt.Color(101, 198, 187));
        NewAccountButton.setFont(new java.awt.Font("Helvetica", 0, 15)); // NOI18N
        NewAccountButton.setForeground(new java.awt.Color(1, 50, 67));
        NewAccountButton.setText("Create new account");
        NewAccountButton.setActionCommand("Simpan");
        NewAccountButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                NewAccountButtonActionPerformed(evt);
            }
        });

        label_name4.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        label_name4.setForeground(new java.awt.Color(255, 255, 255));
        label_name4.setText("Forgot Password ?");

        ForgetPasswordButton.setBackground(new java.awt.Color(101, 198, 187));
        ForgetPasswordButton.setFont(new java.awt.Font("Helvetica", 0, 15)); // NOI18N
        ForgetPasswordButton.setForeground(new java.awt.Color(1, 50, 67));
        ForgetPasswordButton.setText("Retrieve a lost account");
        ForgetPasswordButton.setActionCommand("Simpan");
        ForgetPasswordButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ForgetPasswordButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ForgetPasswordButton, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(NewAccountButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addComponent(label_name4)
                                .addGap(55, 55, 55))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addComponent(label_name18)
                                .addGap(65, 65, 65))))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_name18, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewAccountButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_name4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ForgetPasswordButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(label_name3)
                        .addGap(76, 76, 76))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_name3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean checkTextFieldContain()
    {
        boolean UsernameCondition;
        boolean PasswordCondition;
        if (this.UsernameField.getText().equals("") || this.UsernameField.getText() == null)
        {
            this.UsernameField.setBackground(Color.red);
            UsernameCondition = false;
        }
        else
        {
            this.UsernameField.setBackground(Color.white);
            UsernameCondition = true;
        }

        if (this.PasswordField.getPassword() == null || this.PasswordField.getPassword().length < 1)
        {
            this.PasswordField.setBackground(Color.red);
            PasswordCondition = false;
        }
        else
        {
            this.PasswordField.setBackground(Color.white);
            PasswordCondition = true;
        }

        return UsernameCondition == true && PasswordCondition == true;
    }

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        if (checkTextFieldContain())
        {
            this.InputUC = new UserCredentials(this.UsernameField.getText(), this.PasswordField.getPassword());
            this.Inputed = true;
            this.SessionCond = this.s.newSession(this.InputUC);
            System.out.println("Session : " + this.SessionCond);
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        purge();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void NewAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewAccountButtonActionPerformed
        runRFData();
    }//GEN-LAST:event_NewAccountButtonActionPerformed

    private void runRFCred()
    {
        this.CreateAccountUD = new UserData(
                this.NamaLengkapField.getText(), 
                this.LegalIDField.getText(), 
                this.TTLField.getText(), 
                this.Phone1Field.getText(), 
                this.Phone2Field.getText(), 
                this.WorkField.getText(), 
                this.WorkPlaceField.getText(), this.er);
        
        this.RegisterFormCredentials.setBounds(120, 120, 408, 348);
        this.RegisterFormCredentials.setResizable(false);
        this.RegisterFormCredentials.setModal(true);
        this.RegisterFormCredentials.setVisible(true);
    }
    
    private void runRFData()
    {
        this.RegisterFormData.setModal(true);
        this.RegisterFormData.setResizable(false);
        this.RegisterFormData.setBounds(70, 70, 435, 511);
        this.RegisterFormData.setVisible(true);
    }

    private void ForgetPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForgetPasswordButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ForgetPasswordButtonActionPerformed

    private void RF_btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RF_btnNextActionPerformed
        if(checkRFFields() == true)
        {
            this.RegisterFormData.setVisible(false);
            this.RegisterFormData.dispose();
            runRFCred();
        }
        else
        {
            this.RegisterFormCredentials.setVisible(false);
            this.RegisterFormCredentials.dispose();
        }
    }//GEN-LAST:event_RF_btnNextActionPerformed
   
    private boolean checkRFFields()
    {
        Util u = new Util();
        String Number = "1234567890";
        String WildCard = ",./;-={}:|</;:][>?!@#$%^&*()_+\"\'\\";

        if (this.NamaLengkapField.getText().equals("") || this.NamaLengkapField.getText() == null)
        {
            this.NamaLengkapField.setBackground(Color.red);
            this.NamaLengkapField.setForeground(Color.white);
            return false;
        }
        else
        {
            if (u.checkStringContainString(this.NamaLengkapField.getText(), Number))
            {
                this.NamaLengkapField.setBackground(Color.red);
                this.NamaLengkapField.setForeground(Color.white);
                JOptionPane.showMessageDialog(this.RegisterFormData,
                        "Nama Lengkap Tidak Bisa Memuat Angka",
                        "Form nama Lengkap Error",
                        JOptionPane.ERROR_MESSAGE);
                return false;
            }
            else if (u.checkStringContainString(this.NamaLengkapField.getText(), WildCard))
            {
                this.NamaLengkapField.setBackground(Color.red);
                this.NamaLengkapField.setForeground(Color.white);
                JOptionPane.showMessageDialog(this.RegisterFormData,
                        "Nama Lengkap Tidak Bisa Memuat Karakter Selain Huruf",
                        "Form nama Lengkap Error",
                        JOptionPane.ERROR_MESSAGE);
                return false;
            }
            else
            {
                this.NamaLengkapField.setBackground(Color.white);
                this.NamaLengkapField.setForeground(Color.black);
            }
        }

        if (this.LegalIDField.getText().equals("") || this.LegalIDField.getText() == null)
        {
            this.LegalIDField.setBackground(Color.red);
            this.LegalIDField.setForeground(Color.white);
            return false;
        }
        else
        {
            this.LegalIDField.setBackground(Color.white);
            this.LegalIDField.setForeground(Color.black);
          
        }

        if (this.TTLField.getText().equals("") || this.TTLField.getText() == null)
        {
            this.TTLField.setBackground(Color.red);
            this.TTLField.setForeground(Color.white);
            return false;
        }
        else
        {
            this.TTLField.setBackground(Color.white);
            this.TTLField.setForeground(Color.black);
        }

        if (this.Phone1Field.getText().equals("") || this.Phone1Field.getText() == null)
        {
            this.Phone1Field.setBackground(Color.red);
            this.Phone1Field.setForeground(Color.white);
            return false;
        }
        else
        {
            if (u.checkStringContainString(this.Phone1Field.getText(), u.StandardCharacter)
                    || u.checkStringContainString(this.Phone1Field.getText(), WildCard))
            {
                this.Phone1Field.setBackground(Color.red);
                this.Phone1Field.setForeground(Color.white);
                JOptionPane.showMessageDialog(this.RegisterFormData,
                        "Nomor Telfon 1 Tidak Bisa Memuat Karakter Selain Angka",
                        "Form nama Lengkap Error",
                        JOptionPane.ERROR_MESSAGE);
                return false;
            }
            else
            {
                this.Phone1Field.setBackground(Color.white);
                this.Phone1Field.setForeground(Color.black);
            }
        }

        if (u.checkStringContainString(this.Phone2Field.getText(), u.StandardCharacter)
                || u.checkStringContainString(this.Phone2Field.getText(), WildCard))
        {
            this.Phone2Field.setBackground(Color.red);
            this.Phone2Field.setForeground(Color.white);
            JOptionPane.showMessageDialog(this.RegisterFormData,
                    "Nomor Telfon 1 Tidak Bisa Memuat Karakter Selain Angka",
                    "Form nama Lengkap Error",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else
        {
            this.Phone2Field.setBackground(Color.white);
            this.Phone2Field.setForeground(Color.black);
        }

        if (this.WorkField.getText().equals("") || this.WorkField.getText() == null)
        {
            this.WorkField.setBackground(Color.red);
            this.WorkField.setForeground(Color.white);
            return false;
        }
        else
        {
            this.WorkField.setBackground(Color.white);
            this.WorkField.setForeground(Color.black);
        }

        if (this.WorkPlaceField.getText().equals("") || this.WorkPlaceField.getText() == null)
        {
            this.WorkPlaceField.setBackground(Color.red);
            this.WorkPlaceField.setForeground(Color.white);
            return false;
        }
        else
        {
            this.WorkPlaceField.setBackground(Color.white);
            this.WorkPlaceField.setForeground(Color.black);
        }

        return true;
    }

    private void RF_btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RF_btnCancelActionPerformed
        this.RegisterFormData.setVisible(false);
        this.RegisterFormCredentials.setVisible(false);
        this.RegisterFormData.dispose();
        this.RegisterFormCredentials.dispose();
    }//GEN-LAST:event_RF_btnCancelActionPerformed
    
    private boolean created = false;
    private void RF_btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RF_btnCreateAccountActionPerformed
        if(createAccount())
        {
            JOptionPane.showMessageDialog(this.RegisterFormCredentials,
                        "Akun Berhasil Dibuat",
                        "Success!",
                        JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_RF_btnCreateAccountActionPerformed
    
    private boolean createAccount()
    {
        this.CreateAccountUC = new UserCredentials(
                this.CAUsernameField.getText(),
                new Hash(er).crpytPassword(this.CAConfirmPasswordField.getPassword(), this.CAUsernameField.getText()).toCharArray(),
                this.CAEmailField.getText(),
                this.CreateAccountUD.RegID);
        
        System.out.println(this.CreateAccountUD.RegID);
        this.created = dbud.tambahUserData(this.CreateAccountUD) && dbuc.tambahUserCredentials(this.CreateAccountUC);
        return this.created;
    }
    
    private void RF_btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RF_btnPreviousActionPerformed
        this.RegisterFormCredentials.setVisible(false);
        this.RegisterFormCredentials.dispose();
        this.RegisterFormData.setVisible(true);
    }//GEN-LAST:event_RF_btnPreviousActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Form_login().setVisible(true);
//            }
//        });
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Form_login().setVisible(true);
//            }
//        });
    }
    
    public void purge()
    {
        this.RegisterFormCredentials.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.RegisterFormData.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        super.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        er.debug("Purging All data from form...");
        this.RegisterFormCredentials.dispose();
        this.RegisterFormData.dispose();
        this.dispose();
        super.dispose();
        er.debug("Successfully Purged", 10);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField CAConfirmPasswordField;
    private javax.swing.JTextField CAEmailField;
    private javax.swing.JPasswordField CAPasswordField;
    private javax.swing.JTextField CAUsernameField;
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton ForgetPasswordButton;
    private javax.swing.JTextField LegalIDField;
    private javax.swing.JButton LoginButton;
    private javax.swing.JTextField NamaLengkapField;
    private javax.swing.JButton NewAccountButton;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField Phone1Field;
    private javax.swing.JTextField Phone2Field;
    private javax.swing.JButton RF_btnCancel;
    private javax.swing.JButton RF_btnCreateAccount;
    private javax.swing.JButton RF_btnNext;
    private javax.swing.JButton RF_btnPrevious;
    private javax.swing.JDialog RegisterFormCredentials;
    private javax.swing.JDialog RegisterFormData;
    private javax.swing.JTextField TTLField;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JDialog WaitFrameDialog;
    private javax.swing.JTextField WorkField;
    private javax.swing.JTextField WorkPlaceField;
    private java.awt.Checkbox checkbox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel label_name;
    private javax.swing.JLabel label_name1;
    private javax.swing.JLabel label_name10;
    private javax.swing.JLabel label_name11;
    private javax.swing.JLabel label_name12;
    private javax.swing.JLabel label_name13;
    private javax.swing.JLabel label_name14;
    private javax.swing.JLabel label_name15;
    private javax.swing.JLabel label_name16;
    private javax.swing.JLabel label_name17;
    private javax.swing.JLabel label_name18;
    private javax.swing.JLabel label_name19;
    private javax.swing.JLabel label_name2;
    private javax.swing.JLabel label_name3;
    private javax.swing.JLabel label_name4;
    private javax.swing.JLabel label_name5;
    private javax.swing.JLabel label_name6;
    private javax.swing.JLabel label_name7;
    private javax.swing.JLabel label_name8;
    private javax.swing.JLabel label_name9;
    // End of variables declaration//GEN-END:variables
}
